import type { NextPage } from 'next'
import Head from 'next/head';
import About from './components/About';
import Contact from './components/Contact';
import Footer from './components/Footer';
import Header from './components/Header';
import Hero from './components/Hero';
import Products from './components/Products';
import Team from './components/Team';
import Technologies from './components/Technologies';

const Home: NextPage = () => {
  return (
  <div className='bg-[#24252a] w-screen h-screen text-white overflow-x-hidden snap-mandatory snap-y z-0'>
      <Head>
        <title>xScientist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <section id='home' className='snap-center'>
          <Hero />
        </section>
        <section id='products' className='snap-center'>
          <Products />
        </section>
        <section id='about' className='snap-center'>
          <About />
        </section>
        <section id='technologies' className='snap-center'>
          <Technologies />
        </section>
        <section id='team' className='snap-start'>
        {/* <section id='team'> */}
          <Team />
        </section>
        <section id='contact' className='snap-center'>
          <Contact />
        </section>
      </main>

      <footer className='snap-end bg-black/20 mb-72'>
        <Footer />
      </footer>
    </div>
  )
}


export default Home
